[I3BXGG] Output is not same as hive when data contains '\0'
openlookeng/hetu-core pull request #123
Opened 2021-10-22 03:54 UTC by aman-omer

### What type of PR is this?

/kind bug

### What does this PR do / why do we need it:

Fixes the output when data contains '\0'

### Which issue(s) this PR fixes:

Fixes #I3BXGG

### Special notes for your reviewers:

2021-11-16 05:30 UTC, sraghunandan commented
/sync

2021-11-18 04:44 UTC, Nitin-Kashyap requested changes

2021-11-18 09:56 UTC, aman-omer commented on presto-rcfile/src/main/java/io/prestosql/rcfile/text/StringEncoding.java
> +    private Text unescapeText(Text text)
Moved function to `presto-rcfile/src/main/java/io/prestosql/rcfile/RcFileDecoderUtils.java`

2021-11-18 09:57 UTC, aman-omer commented on presto-rcfile/src/main/java/io/prestosql/rcfile/binary/StringEncoding.java
> +    private Text unescapeText(Text text)
Moved function to `presto-rcfile/src/main/java/io/prestosql/rcfile/RcFileDecoderUtils.java`

2021-11-18 12:03 UTC, sraghunandan commented
/sync

2021-11-22 12:24 UTC, aman-omer commented on presto-hive/src/main/java/io/prestosql/plugin/hive/util/FieldSetterFactory.java
> +        private Text unescapeText(Text text)
I have used 'org.apache.commons.text.StringEscapeUtils'

2021-11-22 12:24 UTC, aman-omer commented on presto-orc/src/main/java/io/prestosql/orc/writer/DictionaryBuilder.java
> +    private int unescapeText(byte[] text)
Done

2021-11-23 04:36 UTC, Nitin-Kashyap commented on presto-orc/src/main/java/io/prestosql/orc/writer/DictionaryBuilder.java
> +        byte[] escapedBytes = escaped.getBytes();
use System.arrayCopy etc

2021-11-23 07:20 UTC, aman-omer commented on presto-orc/src/main/java/io/prestosql/orc/writer/DictionaryBuilder.java
> +        byte[] escapedBytes = escaped.getBytes();
Done

2021-11-25 04:51 UTC, Nitin-Kashyap commented
lgtm

2021-11-25 06:09 UTC, sraghunandan commented
/sync

2021-11-26 10:31 UTC, aman-omer commented on presto-hive/src/main/java/io/prestosql/plugin/hive/GenericHiveRecordCursor.java
> +    private Text escapeText(Text text)
Done

2021-11-26 10:38 UTC, sraghunandan commented
/sync

2021-11-26 14:54 UTC, sraghunandan commented
/sync

2021-11-30 11:41 UTC, sraghunandan commented
/lgtm

2021-11-30 11:41 UTC, sraghunandan commented
/approve

2021-11-30 11:41 UTC, closed without merging